hcup:
  outputs:
    dev:
      type: duckdb
      path: hcup-dev.duckdb
      extensions:
        - httpfs
        - parquet
      external_root: 'D:\git\hcup-dbt\external'
    prod:
      type: duckdb
      path: hcup-prod.duckdb
      extensions:
        - httpfs
        - parquet
      external_root: '\\files.drexel.edu\encrypted\SOPH\UHC\SchnakeMahl_HCUP\Database\Prototype\dbt-external-test\'
  target: dev
